# Backend CI

name: Backend
on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Java 11 projects
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test backend
        run: |
          cd backend
          mvn -B verify --file pom.xml
      - name: Build backend
        run: |
          cd backend
          mvn -B verify --file pom.xml
          mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v1
        with:
          name: BackendArtifact
          path: backend/staging